DROP TABLE IF EXISTS student;
DROP SEQUENCE IF EXISTS student_seq;
DROP SCHEMA IF EXISTS student_tracker;

SET MODE LEGACY
CREATE SCHEMA IF NOT EXISTS student_tracker;
USE student_tracker;

CREATE SEQUENCE student_seq NO CACHE NO CYCLE INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS student (
    id INT NOT NULL DEFAULT student_seq.nextval,
    first_name VARCHAR(255) DEFAULT NULL,
    last_name VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY(id)
);

-- ALTER SEQUENCE STUDENT_TRACKER.STUDENT_SEQ RESTART WITH 1000
-- truncate table STUDENT_TRACKER.STUDENT

SELECT * FROM STUDENT;